use_frameworks!
inhibit_all_warnings!
source 'https://cdn.cocoapods.org/'
workspace 'MLS'

# // MARK: - Example projects

target 'MLS' do
  platform :ios, '11.0'
  pod 'MLSSDK', :path => '..'
  pod 'MLSSDK/IMA', :path => '..'
end

target 'MLS-tvOS' do
  platform :tvos, '11.0'
  pod 'MLSSDK', :path => '..'
  pod 'MLSSDK/IMA', :path => '..'
end


#####################################################################
######## THE FOLLOWING IS NOT NEEDED IN YOUR IMPLEMENTATION! ########
#####################################################################

# // MARK: - Frameworks

target 'MLSSDK-iOS' do
  platform :ios, '11.0'
  project '../MLSSDK.xcodeproj'
  pod 'YouboraLib'
  pod 'YouboraAVPlayerAdapter'
  pod 'Moya', '~> 14.0'
  pod 'Starscream', '~> 3.1'
end

target 'MLSSDK-tvOS' do
  platform :tvos, '11.0'
  project '../MLSSDK.xcodeproj'
  pod 'YouboraLib'
  pod 'YouboraAVPlayerAdapter'
  pod 'Moya', '~> 14.0'
  pod 'Starscream', '~> 3.1'
end

target 'MLSSDK-IMA-iOS' do
  platform :ios, '11.0'
  project '../MLSSDK.xcodeproj'
  pod 'GoogleAds-IMA-iOS-SDK', '~> 3.13'
end

target 'MLSSDK-IMA-tvOS' do
  platform :tvos, '11.0'
  project '../MLSSDK.xcodeproj'
  pod 'GoogleAds-IMA-tvOS-SDK', '~> 4.2'
end


# // MARK: - Tests

target 'Tests' do
  platform :ios, '11.0'
  project '../MLSSDK.xcodeproj'
  pod 'YouboraLib'
  pod 'YouboraAVPlayerAdapter'
  pod 'Moya', '~> 14.0'
  pod 'Starscream', '~> 3.1'
  pod 'Cuckoo', '~> 1.4'
  pod 'Quick', '~> 3.0'
  pod 'Nimble', '~> 8.0'
end

target 'iOSTests' do
  platform :ios, '11.0'
  project '../MLSSDK.xcodeproj'
  pod 'YouboraLib'
  pod 'YouboraAVPlayerAdapter'
  pod 'Moya', '~> 14.0'
  pod 'Starscream', '~> 3.1'
  pod 'Cuckoo', '~> 1.4'
  pod 'Quick', '~> 3.0'
  pod 'Nimble', '~> 8.0'
end

target 'tvOSTests' do
  platform :tvos, '11.0'
  project '../MLSSDK.xcodeproj'
  pod 'YouboraLib'
  pod 'YouboraAVPlayerAdapter'
  pod 'Moya', '~> 14.0'
  pod 'Starscream', '~> 3.1'
  pod 'Cuckoo', '~> 1.4'
  pod 'Quick', '~> 3.0'
  pod 'Nimble', '~> 8.0'
end
